version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing dependencies...
      - npm ci

  build:
    commands:
      - echo Building Angular app...
      - npm run build -- --configuration production
      - echo Copying package.json & package-lock.json to dist
      - cp package.json package-lock.json dist/stolt/

artifacts:
  files:
    - dist/**/*
    - appspec.yml
    - scripts/**/*
    - package*.json 
